- .github/PULL_REQUEST_TEMPLATE.md
- remove code coverage section from pr template
n/a
> chore(pr-template): remove coverage section

- .remarkrc.js
- README.md
- _config.yml
- demo/README.md
- demo/src/App.vue
- demo/src/components/HelloWorld.vue
- package.json
- src/directive.js
- src/directive.spec.js
- src/index.js
- src/install.spec.js
- yarn.lock
- better options reactivity
- callout browser extension
- add remark
- generate toc
n/a
> feat: better options reactivity

- demo/src/main.js
- update options to use test env
> docs: test mode

- README.md
- src/directive.js
- src/index.js
- update install
- update tooltip generation
- update docs
> fix: clean up install method and update docs

- README.md
> docs: add demo link

- README.md
- jest.config.js
- src/api.js
- src/api.spec.js
- src/directive.js
- src/directive.spec.js
- src/index.js
- src/install.spec.js
- add `api.first` method
- add `options.enableGroupedSelectors`
- remove `data-` prefix from attributes
- remove `vue-hubble-id` attribute
- update tests
- update docs
> feat: add api.first and options.enableGroupedSelectors

- demo/package.json
- package.json
> chore: update package.json files

- plugin/src/directive.js
- plugin/src/index.js
- plugin/src/install.spec.js
- refactor tooltips
- refactor event listener bindings
- refactor watch
- clean up code
> fix(directive): handle events and reactive option changes better

- plugin/src/directive.js
- conditionally remove tooltip
> fix(directive): fix copy selector regression

- .github/workflows/node-ci.yml
- README.md
- docs/src/.vuepress/config.js
> fix(docs): 3.x maintenance branch

- .github/workflows/node-ci.yml
- README.md
- docs/src/.vuepress/config.js
- package.json
> fix(docs): urls

- .github/workflows/node-ci.yml
- README.md
- docs/src/.vuepress/config.js
This reverts commit c4fe267cd2cdaa42332c8006d5af5c7922720349, reversing changes made to 0de7d76d5d6f7b15167a977f6ce1e3ad7613268d.
- item
> Revert "Merge pull request #658 from crishellco/cm/maint-test"

- .github/workflows/node-ci.yml
- README.md
- demo/package.json
- docs/package.json
- docs/src/.vuepress/config.js
- package.json
> fix(docs): 3x

- demo/package.json
- docs/package.json
- package.json
> fix: github url

- package.json
- yarn.lock
> fix(deps): updates

- README.md
- docs/src/.vuepress/config.js
> fix(docs): add versions

- docs/src/.vuepress/config.js
- docs/src/.vuepress/theme/index.js
- docs/src/.vuepress/theme/layouts/Layout.vue
> fix(docs): add banner

- README.md
> fix: badges

- plugin/src/directive.js
> fix: remove debugger

- demo/src/main.js
- plugin/src/directive.js
> fix(directive): unwatch

- plugin/src/directive.js
> fix: use get to eval inCorrectEnvironment

- demo/src/main.js
- plugin/src/directive.js
> fix: revert get change

- plugin/src/directive.js
- plugin/src/index.js
> fix(exports): make installer function default export

- vite.config.js
- yarn.lock
> fix(build): make vue external

- README.md
> docs: options api only
